<template>
  <div
    v-if="loading || !image"
    class="
      w-full
      aspect-square
      max-w-lg max-h-lg
      overflow-hidden
      bg-slate-200
      rounded-3xl
      flex
      justify-center
      items-center
    "
  >
    <p class="px-5 text-sm sm:px-10 sm:text-xl">{{ loadingText }}</p>
  </div>
  <img
    v-else-if="image"
    :src="image"
    class="rounded-3xl transition-all w-full max-w-lg max-h-lg"
    :class="{ 'opacity-30': loading }"
    alt="An image of a person generated by AI"
  />
</template>

<script>
export default {
  name: "Image",
  props: {
    loading: {
      type: Boolean,
      required: true,
    },
    loadingText: {
      type: String,
      default: "Loading..."
    },
    image: {
      type: String,
      required: false,
    },
  },
};
</script>

<style>
</style>